In [1]:
import polars as pl

In [3]:
my_szshot = pl.read_parquet("/data/xujiayi/xjy/l2/proc/20260624/szshot_1m.pq")
szshot = pl.read_parquet("/data/xujiayi/xjy/l2/raw/20260624/szshot.pq")

In [4]:
my_szshot

shape: (1_041_165, 42)
┌──────────┬────────────┬───────────┬─────────┬───┬────────────┬──────────┬────────────┬──────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidQty1 ┆ … ┆ BidPrice10 ┆ BidQty10 ┆ AskPrice10 ┆ AskQty10 │
│ ---      ┆ ---        ┆ ---       ┆ ---     ┆   ┆ ---        ┆ ---      ┆ ---        ┆ ---      │
│ time     ┆ i64        ┆ f64       ┆ f64     ┆   ┆ f64        ┆ f64      ┆ f64        ┆ f64      │
╞══════════╪════════════╪═══════════╪═════════╪═══╪════════════╪══════════╪════════════╪══════════╡
│ 09:16:00 ┆ 1          ┆ 11.78     ┆ 10300.0 ┆ … ┆ 10.71      ┆ 10200.0  ┆ 10.68      ┆ 900.0    │
│ 09:17:00 ┆ 1          ┆ 11.78     ┆ 10500.0 ┆ … ┆ 10.71      ┆ 11000.0  ┆ 10.65      ┆ 100.0    │
│ 09:18:00 ┆ 1          ┆ 11.78     ┆ 12300.0 ┆ … ┆ 10.75      ┆ 6000.0   ┆ 10.65      ┆ 100.0    │
│ 09:19:00 ┆ 1          ┆ 11.78     ┆ 12300.0 ┆ … ┆ 10.75      ┆ 6000.0   ┆ 10.64      ┆ 6000.0   │
│ 09:20:00 ┆ 1          ┆ 11.78     ┆ 12300.0 ┆ … ┆ 10.75      ┆ 6700.0   ┆ 10.64      ┆ 6000.0   │
│ …        ┆ …          ┆ …         ┆ …       ┆ … ┆ …          ┆ …        ┆ …          ┆ …        │
│ 14:56:00 ┆ 302132     ┆ 57.98     ┆ 2900.0  ┆ … ┆ 57.85      ┆ 800.0    ┆ 58.1       ┆ 2400.0   │
│ 14:57:00 ┆ 302132     ┆ 57.95     ┆ 6300.0  ┆ … ┆ 57.79      ┆ 200.0    ┆ 58.12      ┆ 9700.0   │
│ 14:58:00 ┆ 302132     ┆ 58.25     ┆ 300.0   ┆ … ┆ 57.9       ┆ 52700.0  ┆ 57.06      ┆ 200.0    │
│ 14:59:00 ┆ 302132     ┆ 58.25     ┆ 300.0   ┆ … ┆ 57.93      ┆ 10100.0  ┆ 57.06      ┆ 200.0    │
│ 15:00:00 ┆ 302132     ┆ 57.95     ┆ 13800.0 ┆ … ┆ 57.79      ┆ 200.0    ┆ 58.1       ┆ 3400.0   │
└──────────┴────────────┴───────────┴─────────┴───┴────────────┴──────────┴────────────┴──────────┘

In [5]:
szshot

shape: (16_025_695, 89)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ UpdateTim ┆ MDStreamI ┆ SecurityI ┆ SecurityI ┆ … ┆ NumOrders ┆ NumOrders ┆ LocalTime ┆ SeqNo    │
│ e         ┆ D         ┆ D         ┆ DSource   ┆   ┆ S9        ┆ S10       ┆ ---       ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ i64      │
│ str       ┆ i64       ┆ i64       ┆ str       ┆   ┆ str       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 08:15:00. ┆ 10        ┆ 2408      ┆ 102       ┆ … ┆ null      ┆ null      ┆ 08:15:00. ┆ 1        │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ 08:15:00. ┆ 10        ┆ 2456      ┆ 102       ┆ … ┆ null      ┆ null      ┆ 08:15:00. ┆ 2        │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ 08:15:00. ┆ 10        ┆ 2565      ┆ 102       ┆ … ┆ null      ┆ null      ┆ 08:15:00. ┆ 3        │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ 08:15:00. ┆ 10        ┆ 2678      ┆ 102       ┆ … ┆ null      ┆ null      ┆ 08:15:00. ┆ 4        │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ 08:15:00. ┆ 10        ┆ 2360      ┆ 102       ┆ … ┆ null      ┆ null      ┆ 08:15:00. ┆ 5        │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 15:39:54. ┆ 10        ┆ 301210    ┆ 102       ┆ … ┆ 1         ┆ 1         ┆ 15:39:55. ┆ 16025691 │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 504       ┆          │
│ 15:39:54. ┆ 10        ┆ 301285    ┆ 102       ┆ … ┆ 1         ┆ 1         ┆ 15:39:55. ┆ 16025692 │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 505       ┆          │
│ 15:39:54. ┆ 10        ┆ 301389    ┆ 102       ┆ … ┆ 4         ┆ 1         ┆ 15:39:55. ┆ 16025693 │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 505       ┆          │
│ 15:39:54. ┆ 10        ┆ 301601    ┆ 102       ┆ … ┆ 1         ┆ 1         ┆ 15:39:55. ┆ 16025694 │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 505       ┆          │
│ 15:39:54. ┆ 10        ┆ 301519    ┆ 102       ┆ … ┆ 1         ┆ 2         ┆ 15:39:55. ┆ 16025695 │
│ 000       ┆           ┆           ┆           ┆   ┆           ┆           ┆ 505       ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘