In [2]:
import polars as pl

In [91]:
my_szshot = pl.read_parquet("/data/xujiayi/xjy/l2/proc/20260624/szshot_1m.pq")

szshot = pl.read_parquet("/data/xujiayi/xjy/l2/raw/20260624/szshot.pq")
szshot= szshot.filter(pl.col('MDStreamID') == 10).with_columns(pl.col('UpdateTime').str.to_time())
cols = ['UpdateTime', 'SecurityID']
for i in range(1, 11):
    cols.extend([f'BidPrice{i}', f'BidVolume{i}', f'AskPrice{i}', f'AskVolume{i}'])
szshot = szshot.select(cols).sort(['SecurityID','UpdateTime'])

In [92]:
szshot = szshot.with_columns([
    pl.col('UpdateTime').dt.hour().alias('hour'),
    pl.col('UpdateTime').dt.minute().alias('minute'),
]).with_columns(
    pl.col('UpdateTime').max().over(['SecurityID','hour','minute']).alias('max_time')
).filter(
    pl.col('UpdateTime') == pl.col('max_time')
).drop('max_time')

In [97]:
MINUTE_NS = 60 * 1_000_000_000

szshot = szshot.with_columns(
    (
        (
            pl.col("UpdateTime").cast(pl.Int64)
            + MINUTE_NS - 1
        )
        // MINUTE_NS
        * MINUTE_NS
    )
    .cast(pl.Time)
    .alias("BarTime")
    ).select(
        "BarTime",
        pl.all().exclude(["BarTime",'UpdateTime'])
)

In [105]:
szshot.filter((pl.col('BarTime')<=pl.time(15,0))).filter(pl.col('SecurityID')==1).sort('BarTime')[60:]

shape: (346, 44)
┌──────────┬────────────┬───────────┬────────────┬───┬────────────┬─────────────┬──────┬────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidVolume1 ┆ … ┆ AskPrice10 ┆ AskVolume10 ┆ hour ┆ minute │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---         ┆ ---  ┆ ---    │
│ time     ┆ i64        ┆ str       ┆ str        ┆   ┆ str        ┆ str         ┆ i8   ┆ i8     │
╞══════════╪════════════╪═══════════╪════════════╪═══╪════════════╪═════════════╪══════╪════════╡
│ 09:16:00 ┆ 1          ┆ 10.720000 ┆ 65100      ┆ … ┆ null       ┆ null        ┆ 9    ┆ 15     │
│ 09:17:00 ┆ 1          ┆ 10.720000 ┆ 67300      ┆ … ┆ null       ┆ null        ┆ 9    ┆ 16     │
│ 09:18:00 ┆ 1          ┆ 10.720000 ┆ 83000      ┆ … ┆ null       ┆ null        ┆ 9    ┆ 17     │
│ 09:19:00 ┆ 1          ┆ 10.720000 ┆ 84500      ┆ … ┆ null       ┆ null        ┆ 9    ┆ 18     │
│ 09:20:00 ┆ 1          ┆ 10.720000 ┆ 83700      ┆ … ┆ null       ┆ null        ┆ 9    ┆ 19     │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …          ┆ …           ┆ …    ┆ …      │
│ 14:57:00 ┆ 1          ┆ 10.530000 ┆ 100        ┆ … ┆ 10.630000  ┆ 85000       ┆ 14   ┆ 56     │
│ 14:58:00 ┆ 1          ┆ 10.540000 ┆ 377823     ┆ … ┆ null       ┆ null        ┆ 14   ┆ 57     │
│ 14:59:00 ┆ 1          ┆ 10.550000 ┆ 535300     ┆ … ┆ null       ┆ null        ┆ 14   ┆ 58     │
│ 15:00:00 ┆ 1          ┆ 10.540000 ┆ 714000     ┆ … ┆ null       ┆ null        ┆ 14   ┆ 59     │
│ 15:00:00 ┆ 1          ┆ 10.510000 ┆ 1016877    ┆ … ┆ 10.610000  ┆ 61300       ┆ 15   ┆ 0      │
└──────────┴────────────┴───────────┴────────────┴───┴────────────┴─────────────┴──────┴────────┘

In [101]:
my_szshot.filter(pl.col('SecurityID') == 1)

shape: (255, 42)
┌──────────┬────────────┬───────────┬────────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidQty1    ┆ … ┆ BidPrice1 ┆ BidQty10 ┆ AskPrice1 ┆ AskQty10 │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ 0         ┆ ---      ┆ 0         ┆ ---      │
│ time     ┆ i64        ┆ f64       ┆ f64        ┆   ┆ ---       ┆ f64      ┆ ---       ┆ f64      │
│          ┆            ┆           ┆            ┆   ┆ f64       ┆          ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ 09:16:00 ┆ 1          ┆ 11.78     ┆ 10300.0    ┆ … ┆ 10.71     ┆ 10200.0  ┆ 10.68     ┆ 900.0    │
│ 09:17:00 ┆ 1          ┆ 11.78     ┆ 10500.0    ┆ … ┆ 10.71     ┆ 11000.0  ┆ 10.65     ┆ 100.0    │
│ 09:18:00 ┆ 1          ┆ 11.78     ┆ 12300.0    ┆ … ┆ 10.75     ┆ 6000.0   ┆ 10.65     ┆ 100.0    │
│ 09:19:00 ┆ 1          ┆ 11.78     ┆ 12300.0    ┆ … ┆ 10.75     ┆ 6000.0   ┆ 10.64     ┆ 6000.0   │
│ 09:20:00 ┆ 1          ┆ 11.78     ┆ 12300.0    ┆ … ┆ 10.75     ┆ 6700.0   ┆ 10.64     ┆ 6000.0   │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ 14:56:00 ┆ 1          ┆ 10.52     ┆ 95600.0    ┆ … ┆ 10.43     ┆ 191800.0 ┆ 10.61     ┆ 56900.0  │
│ 14:57:00 ┆ 1          ┆ 10.53     ┆ 100.0      ┆ … ┆ 10.44     ┆ 49900.0  ┆ 10.63     ┆ 85000.0  │
│ 14:58:00 ┆ 1          ┆ 11.78     ┆ 3500.0     ┆ … ┆ 10.54     ┆ 49600.0  ┆ 10.5      ┆ 7600.0   │
│ 14:59:00 ┆ 1          ┆ 11.78     ┆ 3600.0     ┆ … ┆ 10.58     ┆ 5200.0   ┆ 10.5      ┆ 8100.0   │
│ 15:00:00 ┆ 1          ┆ 10.51     ┆ 1.016877e6 ┆ … ┆ 10.42     ┆ 263700.0 ┆ 10.61     ┆ 61300.0  │
└──────────┴────────────┴───────────┴────────────┴───┴───────────┴──────────┴───────────┴──────────┘