In [2]:
import polars as pl

In [30]:
my_szshot = pl.read_parquet("/data/xujiayi/xjy/l2/proc/20260624/szshot_1m.pq")
szshot = pl.read_parquet("/data/xujiayi/xjy/l2/raw/20260624/szshot.pq").filter(pl.col('MDStreamID') == 10).with_columns(pl.col('UpdateTime').str.to_time())

In [36]:
cols = ['UpdateTime', 'SecurityID']
for i in range(1, 11):
    cols.extend([f'BidPrice{i}', f'BidVolume{i}', f'AskPrice{i}', f'AskVolume{i}'])

szshot = (szshot
    .select(cols)
    .filter(pl.col('SecurityID') == 1)
    #.filter(pl.col('UpdateTime') >= pl.time(9, 31))
)
szshot.sort(pl.col('UpdateTime'))[-50:]

shape: (50, 42)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ UpdateTim ┆ SecurityI ┆ BidPrice1 ┆ BidVolume ┆ … ┆ BidPrice1 ┆ BidVolume ┆ AskPrice1 ┆ AskVolum │
│ e         ┆ D         ┆ ---       ┆ 1         ┆   ┆ 0         ┆ 10        ┆ 0         ┆ e10      │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ time      ┆ i64       ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 14:58:30  ┆ 1         ┆ 10.550000 ┆ 499500    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 14:58:39  ┆ 1         ┆ 10.550000 ┆ 525800    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 14:58:48  ┆ 1         ┆ 10.550000 ┆ 528400    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 14:58:57  ┆ 1         ┆ 10.550000 ┆ 535300    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 14:59:06  ┆ 1         ┆ 10.540000 ┆ 606000    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 15:35:54  ┆ 1         ┆ 10.510000 ┆ 1016877   ┆ … ┆ 10.420000 ┆ 263700    ┆ 10.610000 ┆ 61300    │
│ 15:36:54  ┆ 1         ┆ 10.510000 ┆ 1016877   ┆ … ┆ 10.420000 ┆ 263700    ┆ 10.610000 ┆ 61300    │
│ 15:37:54  ┆ 1         ┆ 10.510000 ┆ 1016877   ┆ … ┆ 10.420000 ┆ 263700    ┆ 10.610000 ┆ 61300    │
│ 15:38:54  ┆ 1         ┆ 10.510000 ┆ 1016877   ┆ … ┆ 10.420000 ┆ 263700    ┆ 10.610000 ┆ 61300    │
│ 15:39:54  ┆ 1         ┆ 10.510000 ┆ 1016877   ┆ … ┆ 10.420000 ┆ 263700    ┆ 10.610000 ┆ 61300    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
my_szshot.filter(pl.col('SecurityID') == 1).filter(pl.col('BarTime') >= pl.time(9, 30))

shape: (241, 42)
┌──────────┬────────────┬───────────┬────────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidQty1    ┆ … ┆ BidPrice1 ┆ BidQty10 ┆ AskPrice1 ┆ AskQty10 │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ 0         ┆ ---      ┆ 0         ┆ ---      │
│ time     ┆ i64        ┆ f64       ┆ f64        ┆   ┆ ---       ┆ f64      ┆ ---       ┆ f64      │
│          ┆            ┆           ┆            ┆   ┆ f64       ┆          ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ 09:30:00 ┆ 1          ┆ 10.68     ┆ 41300.0    ┆ … ┆ 10.59     ┆ 79500.0  ┆ 10.78     ┆ 66500.0  │
│ 09:31:00 ┆ 1          ┆ 10.65     ┆ 392900.0   ┆ … ┆ 10.56     ┆ 99400.0  ┆ 10.75     ┆ 88000.0  │
│ 09:32:00 ┆ 1          ┆ 10.67     ┆ 12000.0    ┆ … ┆ 10.58     ┆ 101300.0 ┆ 10.77     ┆ 83200.0  │
│ 09:33:00 ┆ 1          ┆ 10.68     ┆ 15200.0    ┆ … ┆ 10.59     ┆ 100500.0 ┆ 10.78     ┆ 230100.0 │
│ 09:34:00 ┆ 1          ┆ 10.69     ┆ 2300.0     ┆ … ┆ 10.6      ┆ 517200.0 ┆ 10.79     ┆ 207600.0 │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ 14:56:00 ┆ 1          ┆ 10.52     ┆ 95600.0    ┆ … ┆ 10.43     ┆ 191800.0 ┆ 10.61     ┆ 56900.0  │
│ 14:57:00 ┆ 1          ┆ 10.53     ┆ 100.0      ┆ … ┆ 10.44     ┆ 49900.0  ┆ 10.63     ┆ 85000.0  │
│ 14:58:00 ┆ 1          ┆ 11.78     ┆ 3500.0     ┆ … ┆ 10.54     ┆ 49600.0  ┆ 10.5      ┆ 7600.0   │
│ 14:59:00 ┆ 1          ┆ 11.78     ┆ 3600.0     ┆ … ┆ 10.58     ┆ 5200.0   ┆ 10.5      ┆ 8100.0   │
│ 15:00:00 ┆ 1          ┆ 10.51     ┆ 1.016877e6 ┆ … ┆ 10.42     ┆ 263700.0 ┆ 10.61     ┆ 61300.0  │
└──────────┴────────────┴───────────┴────────────┴───┴───────────┴──────────┴───────────┴──────────┘