In [2]:
import polars as pl

In [116]:
my_szshot = pl.read_parquet("/data/xujiayi/xjy/l2/proc/20260624/szshot_1m.pq")

szshot = pl.read_parquet("/data/xujiayi/xjy/l2/raw/20260624/szshot.pq")
szshot= szshot.filter(pl.col('MDStreamID') == 10).with_columns(pl.col('UpdateTime').str.to_time())
cols = ['UpdateTime', 'SecurityID']
for i in range(1, 11):
    cols.extend([f'BidPrice{i}', f'BidVolume{i}', f'AskPrice{i}', f'AskVolume{i}'])
szshot = szshot.select(cols).sort(['SecurityID','UpdateTime'])

In [117]:
szshot = szshot.with_columns([
    pl.col('UpdateTime').dt.hour().alias('hour'),
    pl.col('UpdateTime').dt.minute().alias('minute'),
]).with_columns(
    pl.col('UpdateTime').min().over(['SecurityID','hour','minute']).alias('min_time')
).filter(
    pl.col('UpdateTime') == pl.col('min_time')
).drop('min_time')

In [118]:
MINUTE_NS = 60 * 1_000_000_000

szshot = szshot.with_columns(
    (
        (
            pl.col("UpdateTime").cast(pl.Int64)
            #+ MINUTE_NS - 1
        )
        // MINUTE_NS
        * MINUTE_NS
    )
    .cast(pl.Time)
    .alias("BarTime")
    ).select(
        "BarTime",
        pl.all().exclude(["BarTime",'UpdateTime'])
)

In [ ]:
szshot.filter(pl.col('SecurityID')==1).sort('BarTime').filter(
    (pl.col('BarTime')>=pl.time(9,29)) & (pl.col('BarTime')<=pl.time(15,0))
)

shape: (332, 44)
┌──────────┬────────────┬───────────┬────────────┬───┬────────────┬─────────────┬──────┬────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidVolume1 ┆ … ┆ AskPrice10 ┆ AskVolume10 ┆ hour ┆ minute │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---        ┆ ---         ┆ ---  ┆ ---    │
│ time     ┆ i64        ┆ str       ┆ str        ┆   ┆ str        ┆ str         ┆ i8   ┆ i8     │
╞══════════╪════════════╪═══════════╪════════════╪═══╪════════════╪═════════════╪══════╪════════╡
│ 09:29:00 ┆ 1          ┆ 10.680000 ┆ 42800      ┆ … ┆ 10.780000  ┆ 66500       ┆ 9    ┆ 29     │
│ 09:30:00 ┆ 1          ┆ 10.670000 ┆ 1900       ┆ … ┆ 10.770000  ┆ 74200       ┆ 9    ┆ 30     │
│ 09:31:00 ┆ 1          ┆ 10.650000 ┆ 392900     ┆ … ┆ 10.750000  ┆ 88000       ┆ 9    ┆ 31     │
│ 09:32:00 ┆ 1          ┆ 10.670000 ┆ 12000      ┆ … ┆ 10.770000  ┆ 83200       ┆ 9    ┆ 32     │
│ 09:33:00 ┆ 1          ┆ 10.680000 ┆ 15200      ┆ … ┆ 10.780000  ┆ 230100      ┆ 9    ┆ 33     │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …          ┆ …           ┆ …    ┆ …      │
│ 14:56:00 ┆ 1          ┆ 10.520000 ┆ 95600      ┆ … ┆ 10.620000  ┆ 121800      ┆ 14   ┆ 56     │
│ 14:57:00 ┆ 1          ┆ null      ┆ null       ┆ … ┆ null       ┆ null        ┆ 14   ┆ 57     │
│ 14:58:00 ┆ 1          ┆ 10.550000 ┆ 477800     ┆ … ┆ null       ┆ null        ┆ 14   ┆ 58     │
│ 14:59:00 ┆ 1          ┆ 10.540000 ┆ 606000     ┆ … ┆ null       ┆ null        ┆ 14   ┆ 59     │
│ 15:00:00 ┆ 1          ┆ 10.510000 ┆ 1016877    ┆ … ┆ 10.610000  ┆ 61300       ┆ 15   ┆ 0      │
└──────────┴────────────┴───────────┴────────────┴───┴────────────┴─────────────┴──────┴────────┘

In [124]:
my_szshot.filter(pl.col('SecurityID') == 1).filter(
    (pl.col('BarTime')>=pl.time(9,30)) & (pl.col('BarTime')<=pl.time(15,0))
)

shape: (241, 42)
┌──────────┬────────────┬───────────┬────────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ BarTime  ┆ SecurityID ┆ BidPrice1 ┆ BidQty1    ┆ … ┆ BidPrice1 ┆ BidQty10 ┆ AskPrice1 ┆ AskQty10 │
│ ---      ┆ ---        ┆ ---       ┆ ---        ┆   ┆ 0         ┆ ---      ┆ 0         ┆ ---      │
│ time     ┆ i64        ┆ f64       ┆ f64        ┆   ┆ ---       ┆ f64      ┆ ---       ┆ f64      │
│          ┆            ┆           ┆            ┆   ┆ f64       ┆          ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ 09:30:00 ┆ 1          ┆ 10.68     ┆ 41300.0    ┆ … ┆ 10.59     ┆ 79500.0  ┆ 10.78     ┆ 66500.0  │
│ 09:31:00 ┆ 1          ┆ 10.65     ┆ 392900.0   ┆ … ┆ 10.56     ┆ 99400.0  ┆ 10.75     ┆ 88000.0  │
│ 09:32:00 ┆ 1          ┆ 10.67     ┆ 12000.0    ┆ … ┆ 10.58     ┆ 101300.0 ┆ 10.77     ┆ 83200.0  │
│ 09:33:00 ┆ 1          ┆ 10.68     ┆ 15200.0    ┆ … ┆ 10.59     ┆ 100500.0 ┆ 10.78     ┆ 230100.0 │
│ 09:34:00 ┆ 1          ┆ 10.69     ┆ 2300.0     ┆ … ┆ 10.6      ┆ 517200.0 ┆ 10.79     ┆ 207600.0 │
│ …        ┆ …          ┆ …         ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ 14:56:00 ┆ 1          ┆ 10.52     ┆ 95600.0    ┆ … ┆ 10.43     ┆ 191800.0 ┆ 10.61     ┆ 56900.0  │
│ 14:57:00 ┆ 1          ┆ 10.53     ┆ 100.0      ┆ … ┆ 10.44     ┆ 49900.0  ┆ 10.63     ┆ 85000.0  │
│ 14:58:00 ┆ 1          ┆ 11.78     ┆ 3500.0     ┆ … ┆ 10.54     ┆ 49600.0  ┆ 10.5      ┆ 7600.0   │
│ 14:59:00 ┆ 1          ┆ 11.78     ┆ 3600.0     ┆ … ┆ 10.58     ┆ 5200.0   ┆ 10.5      ┆ 8100.0   │
│ 15:00:00 ┆ 1          ┆ 10.51     ┆ 1.016877e6 ┆ … ┆ 10.42     ┆ 263700.0 ┆ 10.61     ┆ 61300.0  │
└──────────┴────────────┴───────────┴────────────┴───┴───────────┴──────────┴───────────┴──────────┘